on: [workflow_dispatch]

env: 
  RESOURCE_GROUP_NAME: 'mh-databricks-rg'
  WORKSPACE_NAME: 'mh-databricks-ws'
  RESOURCE_GROUP_LOCATION: 'uaenorth'

name: IaC-Temp
jobs:
  Temp-Job:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Clusters
      uses: azure/CLI@v1
      with: 
        inlineScript: |
          #!/bin/bash
          
          # Install Databricks CLI

          pip install databricks-cli

          # Get Authentication Token

          curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
          https://login.microsoftonline.com/${{ secrets.AZURE_CREDENTIALS_TENANTID }}/oauth2/v2.0/token \
          -d 'client_id=${{ secrets.AZURE_CREDENTIALS_CLIENTID }}' \
          -d 'grant_type=client_credentials' \
          -d 'scope=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d%2F.default' \
          -d 'client_secret=${{ secrets.AZURE_CREDENTIALS_CLIENTSECRET }}' > temp.json
          
          export DATABRICKS_AAD_TOKEN=$(jq -r .access_token temp.json)

          echo "[[MARKS LOGGING]]: Databricks Authentication Token Set"

          # To use az databricks without prompt
          az config set extension.use_dynamic_install=yes_without_prompt

          # Get workspace to json file
          az databricks workspace show --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.WORKSPACE_NAME }} > temp.json

          # Extract workspace ID to environment variable
          export DATABRICKS_HOST="https://"$(jq -r .workspaceUrl temp.json)

          echo "[[MARKS LOGGING]]: Databricks Host Set"

          rm temp.json

          # Configure Databricks
          databricks configure --aad-token --host $DATABRICKS_HOST

          echo "[[MARKS LOGGING]]: Databricks Config file set"

          # Create a cluster
          databricks repos create --url https://github.com/marknhenry/forecasting --provider gitHub --path /Repos/mahenry@microsoft.com

          echo "[[MARKS LOGGING]]: Databricks Workspace and Cluster created successfully"